name: deploying vuepress to qiniu
on:
  push:
    branches:
      - master # master 分支有 push 行为时就触发这个 action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: use Node.js 12.16.0
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.0
      - name: Install
        run: npm install --production=false
      - name: Build
        run: npm run docs:build

      - name: Deploy
        uses: saltbo/uptoc@master
        with:
          driver: qiniu
          region: cn-east-2
          bucket: qiufeng-blue
          exclude: docs/.vuepress/dist/assets
          dist: docs/.vuepress/dist
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.UPTOC_UPLOADER_KEYID }}
          UPTOC_UPLOADER_SK: ${{ secrets.UPTOC_UPLOADER_KEYSECRET }}
